- hosts: localhost
  gather_facts: yes
  pre_tasks:
    - name: create directories
      block:
        - file:
            path: "{{ ansible_env.HOME }}/.config"
            state: directory
        - file:
            path: "{{ ansible_env.HOME }}/.config/nvim"
            state: directory
        - file:
            path: "{{ ansible_env.HOME }}/.local/bin"
            recurse: true
            state: directory

  roles:
    - role: packages
    - role: dotfiles
