- name: install jenv
  git:
    repo: https://github.com/jenv/jenv.git
    version: master
    dest: "{{ ansible_env.HOME }}/.jenv"

- name: Install JDKs
  block:
    - find:
        paths: /opt
        patterns: 'jdk-17.*'
        file_type: directory
      register: jdk_17
    - name: download JDK 17 archive
      become: yes
      unarchive:
        src: "https://download.oracle.com/java/17/latest/jdk-17_linux-{{ ansible_architecture }}_bin.tar.gz"
        remote_src: yes
        dest: /opt
      when: jdk_17.matched == 0

    - find:
        paths: /opt
        patterns: 'jdk-17.*'
        file_type: directory
      register: jdk_17
    - name: Register JDK 17 with jenv
      shell:
        cmd: "jenv add {{ jdk_17.files[0].path }}"

    - find:
        paths: /opt
        patterns: 'jdk-20.*'
        file_type: directory
      register: jdk_20
    - name: download JDK 20 archive
      become: yes
      unarchive:
        src: https://download.oracle.com/java/20/latest/jdk-20_linux-{{ ansible_architecture }}_bin.tar.gz
        remote_src: yes
        dest: /opt
      when: jdk_20.matched == 0

    - find:
        paths: /opt
        patterns: 'jdk-20.*'
        file_type: directory
      register: jdk_20
    - name: Register JDK 20 with jenv
      shell:
        cmd: "jenv add {{ jdk_20.files[0].path }}"

- name: Set JDK 20 as global
  shell:
    cmd: "jenv global 20"
