- name: Install pyenv
  shell:
    cmd: "curl https://pyenv.run | bash"
    creates: "{{ ansible_env.HOME }}/.pyenv"

- name: Install python build prerequisites
  become: yes
  apt:
    name: [libreadline-dev, libncursesw5-dev, libssl-dev, libsqlite3-dev, tk-dev, libgdbm-dev, libc6-dev, libbz2-dev, liblzma-dev]
    state: present

- name: Install Python
  vars:
    pyenv_bin: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv"
  block:
  - find:
      paths: "{{ ansible_env.HOME }}/.pyenv/versions"
      patterns: '3.11.*'
      file_type: directory
    register: python311
  - name: Install python 3.11
    shell:
      cmd: "{{ pyenv_bin }} install 3.11"
    when: python311.matched == 0

  - find:
      paths: "{{ ansible_env.HOME }}/.pyenv/versions"
      patterns: '3.10.*'
      file_type: directory
    register: python310
  - name: Install python 3.10
    shell:
      cmd: "{{ pyenv_bin }} install 3.10"
    when: python310.matched == 0

  - name: Configure global python version
    shell:
      cmd: "{{ pyenv_bin }} global 3.11"