- block:
    - name: Configure zshrc
      import_tasks:
        file: zshrc.yml
    - copy:
        src: "localrc"
        dest: "{{ ansible_env.HOME }}/.localrc"
        force: no
    - copy:
        src: "aliases"
        dest: "{{ ansible_env.HOME }}/.config/aliases"
    - copy:
        src: "vimrc"
        dest: "{{ ansible_env.HOME }}/.vimrc"
    - copy:
          src: "neovim_init.lua"
          dest: "{{ ansible_env.HOME }}/.config/nvim/init.lua"
    - copy:
        src: "tmux.conf"
        dest: "{{ ansible_env.HOME }}/.tmux.conf"
